export type Renderer = 'sw' | 'gl' | 'wg';

export const RENDERER_LABELS: Record<Renderer, string> = {
  sw: 'Software',
  gl: 'WebGL',
  wg: 'WebGPU',
};

export const ANIM_NAMES = [
  '1643-exploding-star',
  '5317-fireworkds',
  '5344-honey-sack-hud',
  '5949',
  '11555',
  '27746-joypixels-partying-face-emoji-animation',
  'R_QPKIVi',
  'abstract_circle',
  'alien',
  'anubis',
  'balloons_with_string',
  'birth_stone_logo',
  'calculator',
  'card_hover',
  'cat_loader',
  'coin',
  'confetti',
  'confetti2',
  'confettiBird',
  'dancing_book',
  'dancing_star',
  'dash-offset',
  'day_to_night',
  'dodecahedron',
  'done',
  'down',
  'dropball',
  'duck',
  'emoji_enjoying',
  'emoji',
  'emoji_wink',
  'fleche',
  'flipping_page',
  'float',
  'fly_in_beaker',
  'focal_test',
  'foodrating',
  'frog_vr',
  'funky_chicken',
  'game_finished',
  'gears',
  'geometric',
  'glow_loading',
  'ghost2',
  'gradient_infinite',
  'gradient_sleepy_loader',
  'gradient_smoke',
  'graph',
  'growup',
  'hamburger',
  'happy',
  'happy_holidays',
  'happy_trio',
  'heart_fill',
  'hola',
  'holdanimation',
  'hourglass',
  'isometric',
  'kote',
  'la_communaute',
  '1f409',
  'like_button',
  'like',
  'loading_rectangle',
  'lolo_walk',
  'lolo',
  'loveface_emoji',
  'material_wave_loading',
  'merging_shapes',
  'message',
  'monkey',
  'morphing_anim',
  'personal_character',
  'polystar_anim',
  'polystar',
  'property_market',
  'pumpkin',
  'ripple_loading_animation',
  'rufo',
  'sample',
  'shutup',
  'skullboy',
  'starburst',
  'starstrips',
  'starts_transparent',
  'StickAndBall',
  'stroke_dash',
  'swinging',
  'text_anim',
  'text2',
  'textblock',
  'textrange',
  'threads',
  'train',
  'uk_flag',
  'voice_recognition',
  'water_filling',
  'waves',
  'yarn_loading',
  'zigzag-smooth',
];

export const URL_PREFIX =
  'https://raw.githubusercontent.com/thorvg/thorvg.web/main/examples/resources/';

export const COUNT_OPTIONS = [10, 20, 50, 100];
export const MIN_SIZE = 50;
export const MAX_SIZE = 300;

export const JANK_MS = 16.67;
export const SEVERE_JANK_MS = 33.33;

export function jankColor(ms: number): string {
  if (ms > SEVERE_JANK_MS) return '#ef4444';
  if (ms > JANK_MS) return '#f59e0b';
  return '#00deb5';
}
